### PR TITLE
Experiment with concurrent parsing using webworkers

### PR DESCRIPTION
**Pull request by aengelberg**
This PR isn't merge-ready just yet, but I want to get your opinion on the idea.

I was curious if there was some way to make the parsing not block the UI thread. At first I assumed there was no way, but I heard about "Web workers" and how they are a (somewhat messy) solution to the problem. Here I have modified instaparse-live to use webworkers. You can try it [here](http://aengelberg.github.io/instaparse-live). Now, each time you edit one of the boxes, instaparse-live sends a web worker to run the parse and report back with the hiccup to render. I used the [servant](https://github.com/MarcoPolo/servant) library, which you may want to read up on right now in order to understand what's going on exactly.

~~The main stumbling block was your inclusion of Codemirror, which meant I had to do some weird cljsbuild magic to make this work. Servant primarily assumes the main app and the servant will run the exact same compiled javascript file (therefore it exposes functions like `webworker?` you can use to determine which component you are in). However, Codemirror throws errors when run on a webworker, because it uses UI-specific JavaScript globals like `document`. So I had to figure out how to exclude Codemirror from the JavaScript file that the worker runs. My workaround was to make two cljsbuild tasks, one for the main app and one for the worker. In only `app.js`, I include a namespace solely dedicated to `:require`ing Codemirror (thus pulling it into the compiled js). In `worker.js`, Codemirror is not pulled in at all, and no errors are thrown because the reagent code that depends on Codemirror is never executed.~~

### CODE REVIEW

**Comment by aengelberg** [comment]
Update: Shortly after posting this, I realized I did not need the double-cljsbuild hack, because I could add the Codemirror js to index.html (thus making it invisible to the worker code). It's much cleaner now. :)

**Comment by aengelberg** [comment]
One downside of this approach is that it is not compatible with figwheel, because figwheel uses `:optimizations :none` and servant does not work with `:optimizations :none` (which is understandable to me given the nature of the script sharing). Perhaps there is a way to fall back to single-threaded parsing if a servant cannot be started up...

**Comment by mhuebert** [comment]
Hey, this is really interesting. I tried `debounce`, and the experience got much worse when I had to stop typing before seeing the update, so I can really see the value of using webworkers. I'm not familiar with them and haven't had a chance yet to read up carefully but I will try to get on that soon!

I am also working on a [branch](https://github.com/mhuebert/instaparse-live/tree/firebase) that uses Firebase to persist editing sessions. It's very very early and unfinished (eg/ no security rules in place on Firebase yet, the links at the top-right don't work yet) but you can cmd-s to save versions & if you copy the link that shows up at the top, get them back again.

**Comment by canweriotnow** [comment]
Watching this evolve is effing beautiful :+1:

**Comment by mhuebert** [comment]
OK, I finally got a chance to take a closer look at this!

The rest of the code has changed a lot, which will mean changes to this PR, but some of the updates paralleled what you did here already: CodeMirror was moved out of the CLJS build to make it easier to use a custom ebnf mode, the parsing function was put into a separate `app.compute` namespace, and parsing output is now stored in a separate `r/atom` (created with `reagent/reaction`).

I _would_ like to try to get figwheel working, because that's my default workflow. Other than that this looks straightforward.

I wonder if it would be worth putting the parse function into a separate build for speed reasons? (I don't yet understand the performance implications or memory usage associated with using workers so I don't know if this is a good idea.)

**Comment by aengelberg** [comment]
Doing spring cleaning of personal PRs, going to close this though anyone can feel free to pick it back up.

**Pull request closed without merging**
